In [2]:
import numpy as np
import math

In [76]:
def LUdecomp(A):
    n = A.shape[0]
    m = A.shape[1]

    pivot = np.zeros(n)
    for i in range(n):
        pivot[i] = i+1

    det = 1
    for j in range(0,n-1):
        p = j
        Amax = abs(A[j,j])
        for k in range(j+1,n):
            if abs(A[k,j]) > Amax:
                Amax = abs(A[k,j])
                p = k
            
        if p != j:
            for k in range(0,m):
                t = A[j,k]
                A[j,k] = A[p,k]
                A[p,k] = t
            
            s = pivot[j]
            pivot[j] = pivot[p]
            pivot[p] = s
            det = -det
        
        det = det*A[j,j]
        if A[j,j] != 0:
            r = 1/A[j,j]
            for i in range(j+1,n):
                mult = A[i,j]*r
                A[i,j] = mult
                for k in range(j+1,m):
                    A[i,k] = A[i,k] - mult*A[j,k]

    det = det*A[n-1,n-1]
    return (A, det, pivot)

def getL(LU):
    n = LU.shape[0]
    m = LU.shape[1]

    L = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            if i == j:
                L[i,j] = 1
            elif i > j:
                L[i,j] = LU[i,j]
    
    return L

def getU(LU):
    n = LU.shape[0]
    m = LU.shape[1]

    U = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            if i <= j:
                U[i,j] = LU[i,j]
    
    return U

def solveL(L, pivot, b):
    n = L.shape[0]

    y = np.zeros(n)
    k = int(pivot[0])
    y[0] = b[k-1]
    for i in range(1,n):
        soma = 0
        for j in range(0,i):
            soma = soma + L[i,j]*y[j]
            
        k = int(pivot[i])
        y[i] = b[k-1] - soma

    return y

def solveU(U, y):
    n = U.shape[0]
    x = np.zeros(n)

    x[n-1] = y[n-1]/U[n-1,n-1]
    for i in reversed(range(0, n-1)):
        soma = 0
        for j in range(i+1, n):
            soma = soma + U[i,j]*x[j]

        x[i] = (y[i] - soma)/U[i,i]

    return x

In [77]:
A = np.array([1., 1., 3., 5., 2., 1., 3., 5., 1.]).reshape(3,3)
b = np.array([-5., 0., -7.])
print(A)
lu, det, pivot = LUdecomp(A)
y = solveL(getL(lu), pivot, b)
print(y)
x = solveU(getU(lu), y)
print(x)

[[1. 1. 3.]
 [5. 2. 1.]
 [3. 5. 1.]]
[ 0.         -7.         -3.89473684]
[ 0.96153846 -1.69230769 -1.42307692]
