In [2]:
import numpy as np

In [18]:
def elimination(A, b):
    # junta a matriz A e o vetor b como uma coluna
    M = np.concatenate((A, b), axis=1)

    print(M)
    # para cada coluna k de 0 a n-1 (que no caso n-2), pois vamos transformar em tringular superior
    # trabalhando coluna por coluna, primeiro zerando os elementos abaixo da diagonal principal
    # na primeira coluna, depois na segunda, mas a ultima coluna não precisa ser zerada pois não
    # existem elementos abaixo da diagonal principal
    for k in range(0, M.shape[0]-1):
        # para cada linha i de k+1 a n (que no caso n-1), começa em k+1 pois zeramos somente abaixo da diagonal principal
        for i in range(k+1, M.shape[0]):
            print("i = ", i, "k = ", k)
            M[i] = M[i] - M[k] * M[i, k] / M[k, k]
            print(M)

    # retorna a matriz A e o vetor b separadamente
    return np.split(M, [M.shape[1]-1], axis=1)

def STS(A, b):
    n = len(b)
    x = np.zeros(n)    

    # i vai variar de n-1 a 0 (por isso o n-1 no primeiro argumento, -1 porque python vai ir até 0, e o último
    # -1 diz que deve decrementar -1 de i a cada iteração), o resto será o que está a direita do x em questão,
    # por isso j vai de i+1 a n (que no caso sera n-1)
    for i in range(n-1, -1, -1):
        rest = sum([A[i, j] * x[j] for j in range(i+1, n)])
        x[i] = (b[i,0] - rest) / A[i,i]
    
    return x

def STI(A, b):
    n = len(b)
    x = np.zeros(n)

    # i vai variar de 0 a n-1, o resto será o que está a esquerda do x em questão
    # logo j vai de 0 a i-1 (é python, então tudo começa em 0 e vai até um valor antes do final)
    for i in range(n):
        rest = sum([A[i, j] * x[j] for j in range(i)])
        x[i] = (b[i,0] - rest) / A[i,i]

    return x

In [19]:
A = np.array([1., -3., 2., -2., 8., -1., 4., -6., 5.]).reshape(3,3)
b = np.array([11., -15., 29.]).reshape(3,1)
A, b = elimination(A, b)
print(STS(A, b))

[[  1.  -3.   2.  11.]
 [ -2.   8.  -1. -15.]
 [  4.  -6.   5.  29.]]
i =  1 k =  0
[[ 1. -3.  2. 11.]
 [ 0.  2.  3.  7.]
 [ 4. -6.  5. 29.]]
i =  2 k =  0
[[  1.  -3.   2.  11.]
 [  0.   2.   3.   7.]
 [  0.   6.  -3. -15.]]
i =  2 k =  1
[[  1.  -3.   2.  11.]
 [  0.   2.   3.   7.]
 [  0.   0. -12. -36.]]
[ 2. -1.  3.]
